### ISSUE TITLE
Broken Links in README

### ISSUE THREAD

**Issue by gordonbanderson** [silverstripe/silverstripe-widgets#119]
There are a couple of links to http://www.silverstripe.org/widgets in README.md, the page no longer exists on the SilverStripe website.

**Comment by tractorcow** [comment]
How does https://github.com/silverstripe/silverstripe-widgets/pull/120 look?

**Comment by gordonbanderson** [comment]
I note there are broken packagist badges on https://github.com/gordonbanderson/silverstripe-widgets/blob/master/docs/en/introduction.md - fix on that page or fix & move them to the main README file?  I think the latter is better for consistency.
