### ISSUE TITLE
Insert Widgets into Footer

### ISSUE THREAD

**Issue by stefanok** [silverstripe/silverstripe-widgets#122]
Sorry im new here - how would i allow widgets in footer?

I have my widgets created ie latest blog posts and gallery which work in sidebar...but stuck on footer?

Stef

**Comment by dhensby** [comment]
Add a new WidetArea and put the $var into the footer template.

The GitHub issue tracker is for bugs rather than support requests. Please see the [community support options](http://www.silverstripe.org/community/#introduction) for help
