### ISSUE TITLE
HtmlEditorField fails to set the correct config upon creation

### ISSUE THREAD

**Issue by torleif** [silverstripe/silverstripe-widgets#129]
If you create a new widget with an HTMLEditorField, it appears like this:

![image](https://cloud.githubusercontent.com/assets/67215/16217177/2fe90b9c-37c5-11e6-8fba-af8d54396401.png)

This is because the HtmlEditorConfig::set_active() is the default, plus the plugins have not been initialized. It should appear like this:

![image](https://cloud.githubusercontent.com/assets/67215/16217224/7f7731f2-37c5-11e6-9b77-4e4bc5ae457f.png)

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-widgets/pull/130
