### ISSUE TITLE
Duplicating a page won't clone widgets

### ISSUE THREAD

**Issue by torleif** [silverstripe/silverstripe-widgets#132]
it will reference the old widgets

**Comment by dhensby** [comment]
I *think* this was fixed... let me look

**Comment by dhensby** [comment]
Yep - so the widgetarea is duplicated and then each widget is iterated over, duplicated and assigned to the new widget area. see https://github.com/silverstripe/silverstripe-widgets/blob/master/code/extension/WidgetPageExtension.php#L53-L69
