### ISSUE TITLE
Widgets randomly disapearing

### ISSUE THREAD

**Issue by torleif** [silverstripe/silverstripe-widgets#136]
I've had two instances of this happening, a CMS editor makes a change to a widget, clicks save draft and loses all the content.

One was on Mac OS X / chrome, the second Windows 7 / firefox. 

I suspect there must be a scenario in saveInto(...) in WidgetAreaEditor.php where it will cause all the widgets to be deleted. 

I think a fix should be to use javascript to explicitly tell the widget editor to delete widgets.

**Comment by dhensby** [comment]
> I think a fix should be to use javascript to explicitly tell the widget editor to delete widgets.

I think this could be difficult to achieve.

Are you suffering from the issue where more than one page is related to the same `WidgetArea`? (this can happen when you duplicate a page in the CMS).

**Comment by torleif** [comment]
@dhensby sadly no, in both cases each CMS editor claimed to have just been editing the single widget on each page.

**Comment by dhensby** [comment]
So they were editing one widget and they all disappeared or they were editing one widget and it disappeared?

Are the widgets bespoke? Is there any kind of custom logic around them that could result in this? Are the widgets actually being *deleted* or just un-linked from the widget area?

Is this something you can reproduce on a fresh install?

**Comment by torleif** [comment]
The were editing a single widget and the entire widget area was cleared. 

The widgets are all customised, they're mostly text fields, htmltext fields etc. I'll have a detailed look and see if I can see if they've been unlinked or deleted tomorrow.

**Comment by torleif** [comment]
It looks like the widget areas were retained, but the widgets themselves were deleted.

**Comment by dhensby** [comment]
Hmm, so the widgets are definitely being deleted.

It's hard to really know how or why this is happening without seeing it. Is it something you're prepared to investigate?

**Comment by torleif** [comment]
Because I can't reproduce this issue, I'll close it.

I'll be using the 'strips' for this sort of functionality going forward in the future, as I'm worried more people will lose data.
