### ISSUE TITLE
Expression #1 of SELECT list is not in GROUP BY clause

### ISSUE THREAD

**Issue by digi-brains** [silverstripe/silverstripe-widgets#144]
Activating the 'Archive' widget produces this error:

`Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'abcdxyz.BlogPost_Live.PublishDate' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by`

MySQL server version: 5.7.17-0ubuntu0.16.04.1 - (Ubuntu)

**Comment by micahsheets** [comment]
I am also getting this error with the widgets module and MySQL version 5.7

**Comment by robbieaverill** [comment]
Hey @digi-brains + @micahsheets - which version of SilverStripe and widgets are you using?

**Comment by LABCAT** [comment]
hi @robbieaverill I am also getting this error with same server configuration. I am using tag 1.2.5 of widgets.

**Comment by dhensby** [comment]
Related: #5451

This is because MySQL 5.7 has changed it's default behaviour

**Comment by digi-brains** [comment]
@robbieaverill 1.2.4

**Comment by micahsheets** [comment]
I installed silverstripe 3.6.0 with composer set to * for both blog and widgets.

**Comment by dhensby** [comment]
> I installed silverstripe 3.6.0 with composer set to * for both blog and widgets.

we need to know which version is installed. `composer show` might show you which version is installed

**Comment by micahsheets** [comment]
SS 3.6.0

Blog 2.4.5

Widgets 1.2.5


Micah Sheets





Sonic Eye Technologies
2647 E 33rd Ave.
Spokane, WA  99223
509-939-4739
micah@soniceyetec.biz <mailto:micah@soniceyetec.biz>

**Comment by digi-brains** [comment]
Sorry...forgot to add which SS and blog version...

SS: 3.5.3
Widgets: 1.2.4
Blog: 2.4.5

**Comment by robbieaverill** [comment]
Fixed by https://github.com/silverstripe/silverstripe-blog/pull/446
