### ISSUE TITLE
Method 'getRequest' does not exist on 'SilverStripe\Forms\Form'

### ISSUE THREAD

**Issue by afoster** [silverstripe/silverstripe-widgets#147]
Hi,

I'm running widgets (dev-master) under Silverstripe 4.0.0-alpha6. I've installed the blog module as an easy way to get some test widgets.

I have my `Page`:

```
<?php

use SilverStripe\CMS\Model\SiteTree;
use SilverStripe\Widgets\Forms\WidgetAreaEditor;
use SilverStripe\Widgets\Model\WidgetArea;

class Page extends SiteTree
{

    private static $has_one = array(
        'TestWidgetArea' => WidgetArea::class
    );

    private static $db = array(
    );

    public function getCMSFields()
    {
        $fields = parent::getCMSFields();
        $fields->addFieldToTab('Root.Widgets', new WidgetAreaEditor('TestWidgetArea'));
        return $fields;
    }
}
```

I can drag and drop a widget into the area. However, when I try to save draft or publish I get an error on the xhr call:

ERROR [Emergency]: Uncaught BadMethodCallException: Object->__call(): the method 'getRequest' does not exist on 'SilverStripe\Forms\Form'
IN POST /admin/pages/edit/EditForm/
Line 57 in /path/to/public_html/framework/src/Core/CustomMethods.php

Thanks

**Comment by robbieaverill** [comment]
The SS4 compatible branch was made a few alphas ago - it needs to be updated again

**Comment by gaethofs** [comment]
Changing the `getRequest()` method to `getRequestHandler()->getRequest() ` on line 145 in SilverStripe\Widgets\Forms\WidgetAreaEditor silences this error, but while saving an added widget succeeds, it doesn't really seem to add the widget.

**Comment by tractorcow** [comment]
You can also do Controller::curr()->getRequest().

getRequest() is being added back to form soon, actually.

**Comment by robbieaverill** [comment]
This should be fixed now. Please feel free to reopen if you're still having problems.
