### ISSUE TITLE
ENHANCEMENT Apply Versioned extension to Widget model (v4 only)

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-widgets#148]
With the new ownership model in place, it should be simple to apply versioned and and ownership relationship between pages and widgets.

https://docs.silverstripe.org/en/4/developer_guides/model/versioning/#dataobject-ownership

Replaces https://github.com/silverstripe/silverstripe-cms/issues/322

**Comment by robbieaverill** [comment]
@tractorcow do you think this is worth doing before 2.0.0 stable for widgets on SS4?

**Comment by tractorcow** [comment]
Yes it should probably be out of the box 4.0 onwards.

**Comment by robbieaverill** [comment]
Pull request at #163, will need to have #162 merged first and possibly rebased
