### ISSUE TITLE
SS4 WidgetAreaEditor missing namespace

### ISSUE THREAD

**Issue by adrian-stein** [silverstripe/silverstripe-widgets#157]
I am running 2.x-dev and am getting the error `[Alert] Class 'SilverStripe\Widgets\Forms\Requirements' not found`
It appears to need `use SilverStripe\View\Requirements;` as the requirements in the FieldHolder method need it to work.

**Comment by robbieaverill** [comment]
Yep, makes sense. Would you be keen to make a pull request?

**Comment by robbieaverill** [comment]
Fixed in #158
