### ISSUE TITLE
Check and update module for SS4 compatibility where necessary

### ISSUE THREAD

**Issue by rupachup** [silverstripe/silverstripe-widgets#160]
## Acceptance Criteria

- [x] Works on SS4
- [x] Beta tag released

## Sub tasks

- [x] #159 
- [x] ~~Saving a page with new widgets redirects to 404~~ couldn't reproduce

## Pull requests

- [x] #161

**Comment by robbieaverill** [comment]
https://github.com/silverstripe/silverstripe-widgets/releases/tag/2.0.0-beta1
