### ISSUE TITLE
Rename HTML Content widget

### ISSUE THREAD

**Issue by raissanorth** [silverstripe/silverstripe-widgets#165]
The title of the **HTML Content** widget is not an issue as such, but potentially confusing. 
As a first time user, I expected it would render the HTML content I entered in the input field. 🙄

Perhaps a rename to something like **Formatted Text Widget**  would prevent other newbies making similar assumptions.

**Comment by robbieaverill** [comment]
True, this is probably a title created by a developer :-) what about “Content widget” ?

**Comment by raissanorth** [comment]
That works as well. What do you think, @clarkepaul and @sachajudd?

**Comment by clarkepaul** [comment]
"Content widget" works, we typically use "Content" as a label for the WYSIWYG on pages.

**Comment by robbieaverill** [comment]
PR at https://github.com/silverstripe/silverstripe-content-widget/pull/18

**Comment by robbieaverill** [comment]
@clarkepaul how about "Rich content widget"?

**Comment by clarkepaul** [comment]
From my understanding this title isn't seen by admins in the UI? They see "Content" as the title of the WYSIWYG field typically right? 

Sorry not sure if I've got the right understanding here.

**Comment by robbieaverill** [comment]
Yeah sorry the CMS users to see it:

![image](https://user-images.githubusercontent.com/5170590/52682352-b79f6f80-2f71-11e9-8a8b-d70ded1671ea.png)

**Comment by clarkepaul** [comment]
Right, okay. I probably would have gone for "Formatted content" as the opposite to Plain text, but Rich content is pretty usable as well. Can't we just call it "Content" as we do the rest of the CMS? sorry not helping much here.

**Comment by robbieaverill** [comment]
"Content" it is :)
