### ISSUE TITLE
Can't install for SS2.3 and blog2.5

### ISSUE THREAD

**Issue by nimeso** [silverstripe/silverstripe-widgets#171]
The client does not have the cash to upgrade to SS4 so I'm stuck with SS3.6.2
I have installed Blog 2.5 but when I try and install Widgets1.3 I get the following errors:

`PS D:\xamppfin\htdocs\silverdelta> composer require silverstripe/widgets:1.3
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing darianno/ss-bs (dev-master 2ab1a1c)
    Cloning 2ab1a1ceb8a86ba8d08e8f95ec1eb63e6fb2f0ef from cache
    2ab1a1ceb8a86ba8d08e8f95ec1eb63e6fb2f0ef is gone (history was rewritten?)
    Failed to download darianno/ss-bs from source: Failed to execute git checkout "2ab1a1ceb8a86ba8d08e8f95ec1eb63e6fb2f0ef" -- && git reset --hard "2ab1a1ceb8a86ba8d08e8f95ec1eb63e6fb2f0ef" --`

**Comment by robbieaverill** [comment]
Hi there, this error is not caused by a SilverStripe module. It looks like you’re using a private fork or project which is gone it changed. Thanks for taking the time to log the issue though
