### ISSUE TITLE
Translatable support: Widget's added to homepage don't have correct Locale

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-widgets#22]
Migrated from http://open.silverstripe.org/ticket/6470

Adding widgets to the homepage in one language are not recognized in the non-default language. Fix is to add this code to sapphire/widgets/Widget.php . See  http://www.silverstripe.org/widgets-2/show/11375

```
function onBeforeWrite() {

  parent::onBeforeWrite();

  // Set locale from the currently choosen language locale 
if ($this->Locale != Translatable::get_current_locale()) $this->Locale = Translatable::get_current_locale();
}
```

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
