### ISSUE TITLE
Second widget on one page doesn't work

### ISSUE THREAD

**Issue by Friksel** [silverstripe/silverstripe-widgets#29]
I use Silverstripe 3.0.3 stable release with the widgetmodule. 
I've created several widgets wich function properly when used on a page. 
But when I add several widgets to the same page the second widget fails. 
I found out the functions are not being called of the second widget or that the objects not exist.

On this forum I also found this forum item: 
http://www.silverstripe.org/widgets-2/show/20989 
this seem to be the same problem.

Next to puting 2 widgets into one widgetarea, I also tried putting 2 widgetareas (each with one widget). 
But that doesn't help.

It seems like 2 or more widgets on a page aren't possible. 

Please! Make it work!!!!

**Comment by robbieaverill** [comment]
Feel free to reopen if this still affects anyone on more recent versions of SilverStripe
