### ISSUE TITLE
'Available Widgets' and 'Widgets Currently Used' doubling up in admin (blog page type)

### ISSUE THREAD

**Issue by matt-bailey** [silverstripe/silverstripe-widgets#37]
I'm not sure if this is a problem with the widgets module or the blog module, but the 'Available Widgets' and 'Widgets Currently Used' areas are doubling up in Admin on the blog page type (see screen grab below).

This is a vanilla SS 3.0.5 install with the blog, comments and widgets modules installed. It's using the Simple theme.

![SilverStripe - Edit Page](https://f.cloud.github.com/assets/969385/189636/c5fd2136-7e9b-11e2-89e7-10866fc82517.png)

**Comment by robbieaverill** [comment]
I can't reproduce this any more on SilverStripe 3.6.0, feel free to reopen if this is still affecting you
