### ISSUE TITLE
function in WidgetClass extends Widget not returning value

### ISSUE THREAD

**Issue by oceanmountain** [silverstripe/silverstripe-widgets#39]
I was trying to return a function in my widget to display certain members. However, when I put this in MyWidget and looped through it in the widget template I did not get any results.
However, putting the function to get the members in the MyWidget_controller, it all worked!

More info: http://www.silverstripe.org/widgets-2/show/22718 (with code and stuff).
Not sure if this is an issue though, perhaps it is maybe it should be like this

**Comment by robbieaverill** [comment]
Closing as this doesn't sound like a bug
