### ISSUE TITLE
When widget added/removed/edited CMS buttons don't change to reflect this

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-widgets#43]
Normally when a field in the CMS is changed the save / save & publish buttons change to highlight that changes need to be saved.

This does not happen when widgets are changed

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
