### ISSUE TITLE
Support lots of widgets on left hand side area editor. Scrollbar perhaps?

### ISSUE THREAD

**Issue by wilr** [silverstripe/silverstripe-widgets#47]
Original ticket: http://open.silverstripe.org/ticket/8348

When more than about 8 widgets are installed (through being on the file system), the left hand side of "available widgets" in the CMS creates a scroll bar, but you cannot drag the items to the right.

I suggest making the left and right hand side have independent scrollbars when they exceed their heights.

Secondly, if you drag the widget to any place underneath the right hand side, let it stick. Currently, you must drag it very close to an existing installed widget, which is poor usability.

**Comment by robbieaverill** [comment]
We don't have drag and drop any more, so clicking the `+` button would be fine in a scrolling context. Feel free to reopen if I've misunderstood!
