### ISSUE TITLE
Pages with widgets that have been duplicated generate notice on draft delete, breaks CMS hierarchy until browser cache flush

### ISSUE THREAD

**Issue by clyonsEIS** [silverstripe/silverstripe-widgets#71]
SS3.1.2-rc2
widgets - master branch, last commit: 2c08c173fb064bdcb0ad2a8c474339c1296a6cf4

To reproduce:
-Clean install w/ widgets module only, add generic Page extension
-Duplicate any page (not necessary to actually add any widgets)
-Delete draft (or save & publish, unpublish, delete draft)
*Notice appears, CMS SiteTree hierarchy controls disappear until browser cache flush (which often requires closing the tab or whole browser)

Maybe related to versioning?

Trace:
https://gist.github.com/clyonsEIS/1062e28c596ef6980ec0

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
