### ISSUE TITLE
Doest support has_many relationship 

### ISSUE THREAD

**Issue by selay** [silverstripe/silverstripe-widgets#72]
If you have a has_many relationship, it fails to work and show a tab to select from existing data object. Even if you try to add it "manually" in getCMSFields(), it still doesnt work, throwing errors like: Fatal error: Call to a member function FormAction() on a non-object in .... framework\forms\FormField.php on line 161

**Comment by robbieaverill** [comment]
Hi @selay, I'm going to close this due to inactivity. If you're still experiencing this problem feel free to reopen, and please provide the version of SilverStripe core and subsites that you're using. Thanks!
