### ISSUE TITLE
Loop Children / with has_one (page) not working

### ISSUE THREAD

**Issue by oceanmountain** [silverstripe/silverstripe-widgets#81]
While inside the template of a widget it is impossible to use <% loop Children %>, or when using a has_one relationship to page to do <% with HasOnePage %>.

**Comment by dhensby** [comment]
What would the children relate to in the context of a widget? 

It's worth investigating the has one problem.

**Comment by jameshoward** [comment]
I think I'm seeing similar with the `has_one` issue. I have a `has_one` on my widget class called `ExplorePage`. In the template I can output `$ExplorePageID` and I get the correct ID of the page but if I try `$ExplorePage.Title` it outputs nothing, as though the ID is correct but it cannot load its relationship.

**Comment by dhensby** [comment]
This is coming up to a year old without feedback. @oceanmountain anything to add or shall I close this?

**Comment by tractorcow** [comment]
Use `$CurrentPage.Children` in your template to get that. :)
