### ISSUE TITLE
Tests fail under silverstripe-framework 3 branch

### ISSUE THREAD

**Issue by UndefinedOffset** [silverstripe/silverstripe-widgets#86]
Per the @wilr's comment in #85 the DB=MYSQL CORE_RELEASE=3 build is failing, at first I thought changing WidgetArea::ItemsToRender() to use filter() would solve the deprecation issues and allow the build to finish but it would seem that just moves to the next issue. Which is bellow, it would seem as though the silverstripe/framework 3 branch has a deprecation on has_one(). If it doesn't disappear the build log can be seen here https://travis-ci.org/webbuilders-group/silverstripe-widgets/jobs/56909007

```
WidgetControllerTest::testWidgetFormSubmission
DataObject->has_one is deprecated. Please use hasOne() instead. Called from WidgetContentControllerExtension->handleWidget.
```

**Comment by wilr** [comment]
Can use hasMethod or something to switch between the two. Not sure if that deprecation is worth having a new branch for.

**Comment by dhensby** [comment]
You could turn off deprecation errors for the test

**Comment by chillu** [comment]
Fixed through https://github.com/silverstripe/silverstripe-widgets/commit/f2f6b6e18c143bc720c590f85572d39b026d3d44 and https://github.com/silverstripe/silverstripe-widgets/commit/d0ce44401fe987eed0e0a6a6150d318b7067ac55.

There's one branch for ~3.2 and ~4.0 at the moment (master). In general, I don't think its a good idea to disable deprecation warnings for tests - it'll just give devs an excuse to turn them off altogether if not even our core modules are free of warnings. We shouldn't have introduced deprecations in a 3.x minor release, which is causing heaps of downstream problems in modules now (and unnecessary branching).
