### ISSUE TITLE
more than one widget does not seem to work 

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-widgets#88]
Widgets dont seem to work when there is more than one. No idea why, abandoning the use of widgets because there seem to be too many pitfalls.

**Comment by assertchris** [comment]
I can't reproduce this error, using `3.1.x-dev` framework/CMS and `master` blog. What about widgets doesn't work? Do you get an error? Is the template rendered incorrectly?

**Comment by sunnysideup** [comment]
Sorry for the cryptic message. We had widgets loaded onto a site and only the first one (or last on - can remember) would show on the front-end.  Also, the use of some fields (e.g. treedropdownfield) does not work on widgets.

**Comment by assertchris** [comment]
Thanks for the info, I'll check it out again.

**Comment by sunnysideup** [comment]
the treedropdownfield error (and other form fields) is documented all over the place, it has something to do with the "form" object not being available to the field object.

**Comment by MattyBalaam** [comment]
I remember having this issue in the past, a solution for me was to make sure each widget $Content was in a uniquely named element: http://www.silverstripe.org/community/forums/widgets-2/show/16123#post309314

**Comment by robbieaverill** [comment]
Hi @sunnysideup @MattyBalaam, I'm going to close this as it's fairly old and stale now. If this is still an issue, please feel free to reopen. Thanks!
