### ISSUE TITLE
CMS Fields validation for widgets.

### ISSUE THREAD

**Issue by SteveAzz** [silverstripe/silverstripe-widgets#92]
Is it possible to have validation for the fields found in the CMS for a specific widget. 

I have tried the usual method for each Dataobject but it doesn't seem to be working. 

```
public function getCMSValidator(){
}
```

**Comment by robbieaverill** [comment]
@SteveAzz if this is a question it might be more suitable for SilverStripe forums, the community Slack channel or Stackoverflow. If this is a bug report, please provide a version and enough code to reproduce the error. Thanks :)
